# Spotify Song Recommendation Project Configuration

#data paths
dataset_path: "dataset/data" 
processed_data_path: "processed_data" 

#data sampling
num_records: 10  # set to an integer to limit records processed (e.g. 100000); null processes all

#spark config
spark_driver_memory: "4g"
spark_shuffle_partitions: 8
spark_parquet_block_size: 33554432  # 32 MB